version: '2'

services:
  api:
    build: .
    image: ghcr.io/luxonis/tools_api:latest
    ports:
      - 8000:8000
    environment:
      SENTRY_TOKEN: ${SENTRY_TOKEN}
  yolov7:
    build: ./yolov7
    image: ghcr.io/luxonis/tools_yolov7:latest 
    ports:
      - 8001:8001
    environment:
      SENTRY_TOKEN: ${SENTRY_TOKEN}
  nginx:
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - api
      - yolov7
    volumes:
      - ./log:/log:z
      - /etc/letsencrypt/live/tools.luxonis.com/privkey.pem:/ssl/key.pem
      - /etc/letsencrypt/live/tools.luxonis.com/fullchain.pem:/ssl/cert.pem
